const contractData = {
  // Contract Metadata
  metadata: {
    con_index: 6,
    title: "Non-Disclosure Agreement",
    type: "NDA",
    identifier: "English, bilateral",
    sort: "Individual",
    version: "0.2",
    status: "Draft",
    created_date: "2020-11-23",
    last_modified: "2020-12-02",
    document_code: "c-20-ad-1-nda-1",
    author: "Michael Zollner",
    language: "EN",
    applicable_law: "GER",
    jurisdiction: "Munich",
    note: "Michael Zollner, 02.12.20: This NDA draft is based on a template"
  },

  // Parties to the Agreement
  parties: [
    {
      party_index: 1,
      con_index: 6,
      party_id: "party-1",
      party_type: "discloser",
      party_name: "ndaDesk GmbH",
      party_registered_office: "Müller Street 32, 81234 Munich, Germany",
      party_registration_number: "HDS21342230",
      party_represented_by: "Philipp Fontaine",
      party_role: "PARTY 1",
      party_approved: true,
      party_signed: false
    },
    {
      party_index: 2,
      con_index: 6,
      party_id: "party-2",
      party_type: "recipient",
      party_name: "Dirk Hoffmann Consulting GbR",
      party_registered_office: "Beer Street 100, 89100 Munich, Germany",
      party_registration_number: null,
      party_represented_by: "Dirk Hoffmann",
      party_role: "PARTY 2",
      party_approved: true,
      party_signed: false
    }
  ],

  // Agreement Terms
  terms: {
    term_index: 1,
    con_index: 6,
    effective_date: "2022-01-01",
    expiration_date: "2022-12-31",
    confidentiality_period: "5 years",
    disclosure_period: "3 years",
    termination_notice: "3 months written notice",
    penalty: null,
    confidential_information_scope: "comprehensive",
    change_of_control_termination: true
  },

  // Sections Hierarchy
  sections: [
    {
      sec_index: 100,
      sec_con_index: 6,
      sec_header: "Preamble",
      sec_parent_index: null,
      sec_point: "A",
      sec_order: 1,
      sec_type: "preamble"
    },
    {
      sec_index: 101,
      sec_con_index: 6,
      sec_header: "Definitions and Interpretations",
      sec_parent_index: null,
      sec_point: "B",
      sec_order: 2,
      sec_type: "definitions"
    },
    {
      sec_index: 102,
      sec_con_index: 6,
      sec_header: "Main Clauses",
      sec_parent_index: null,
      sec_point: "C",
      sec_order: 3,
      sec_type: "clauses"
    },
    {
      sec_index: 103,
      sec_con_index: 6,
      sec_header: "Duties and Obligations",
      sec_parent_index: 102,
      sec_point: "C.I",
      sec_order: 1,
      sec_type: "subsection"
    },
    {
      sec_index: 104,
      sec_con_index: 6,
      sec_header: "Assignment of Rights or Obligations",
      sec_parent_index: 102,
      sec_point: "C.II",
      sec_order: 2,
      sec_type: "subsection"
    },
    {
      sec_index: 105,
      sec_con_index: 6,
      sec_header: "Severability",
      sec_parent_index: 102,
      sec_point: "C.III",
      sec_order: 3,
      sec_type: "subsection"
    },
    {
      sec_index: 106,
      sec_con_index: 6,
      sec_header: "Change of Control",
      sec_parent_index: 102,
      sec_point: "C.IV",
      sec_order: 4,
      sec_type: "subsection"
    },
    {
      sec_index: 107,
      sec_con_index: 6,
      sec_header: "Term and Termination",
      sec_parent_index: 102,
      sec_point: "C.V",
      sec_order: 5,
      sec_type: "subsection"
    },
    {
      sec_index: 108,
      sec_con_index: 6,
      sec_header: "Entire Agreement",
      sec_parent_index: 102,
      sec_point: "C.VI",
      sec_order: 6,
      sec_type: "subsection"
    },
    {
      sec_index: 109,
      sec_con_index: 6,
      sec_header: "Governing Law and Jurisdiction",
      sec_parent_index: 102,
      sec_point: "C.VII",
      sec_order: 7,
      sec_type: "subsection"
    },
    {
      sec_index: 110,
      sec_con_index: 6,
      sec_header: "No License",
      sec_parent_index: 102,
      sec_point: "C.VIII",
      sec_order: 8,
      sec_type: "subsection"
    },
    {
      sec_index: 111,
      sec_con_index: 6,
      sec_header: "No Obligation to Proceed",
      sec_parent_index: 102,
      sec_point: "C.IX",
      sec_order: 9,
      sec_type: "subsection"
    },
    {
      sec_index: 112,
      sec_con_index: 6,
      sec_header: "Remedies",
      sec_parent_index: 102,
      sec_point: "C.X",
      sec_order: 10,
      sec_type: "subsection"
    }
  ],

  // Preamble Items (WHEREAS clauses)
  preamble: [
    {
      preamble_index: 1,
      preamble_con_index: 6,
      preamble_sec_index: 100,
      preamble_point: "A.1",
      preamble_order: 1,
      preamble_type: "whereas",
      preamble_text: "<p>WHEREAS, the RELATIONSHIP is governed by a [kind of contract] dated [date] between the PARTIES (hereinafter referred to as \"the RELATIONSHIP AGREEMENT\").</p>",
      preamble_status: "placeholder",
      preamble_negotiable: true,
      preamble_short: "Reference to underlying business relationship",
      preamble_info: "Specifies the primary commercial agreement between parties",
      preamble_meta: "<p>Contractual foundation reference</p>",
      preamble_playbook: "<p>Specify the nature of the underlying business relationship (e.g., Master Services Agreement, Development Agreement, Distribution Agreement). Ensure the referenced contract is properly executed and in force. Common mistake: referencing a contract that hasn't been signed yet.</p>",
      preamble_fallback: "General business relationship",
      preamble_accountable: "Legal, Business Development",
      preamble_approval: false,
      preamble_text__vs: "<p>WHEREAS, the RELATIONSHIP is governed by a Master Services Agreement dated January 1, 2022 between the PARTIES (hereinafter referred to as \"the RELATIONSHIP AGREEMENT\").</p>",
      preamble_approval__vs: true,
      preamble_comment: null,
      preamble_comment__vs: "Specific contract type and date added for clarity",
      preamble_compare: "Version 2 specifies MSA and exact date vs. placeholder.",
      preamble_timestamp: null,
      preamble_updated: false
    },
    {
      preamble_index: 2,
      preamble_con_index: 6,
      preamble_sec_index: 100,
      preamble_point: "A.2",
      preamble_order: 2,
      preamble_type: "whereas",
      preamble_text: "<p>WHEREAS, the PARTIES expect that in the course of the RELATIONSHIP, each PARTY will provide the other with CONFIDENTIAL INFORMATION.</p>",
      preamble_status: "final",
      preamble_negotiable: false,
      preamble_short: "Acknowledgment of information exchange",
      preamble_info: "Standard acknowledgment that confidential information will be shared",
      preamble_meta: "<p>Information exchange premise</p>",
      preamble_playbook: "<p>Standard language acknowledging mutual exchange of confidential information. Generally non-negotiable as it establishes the fundamental premise of the NDA. Sets expectation that both parties will be disclosing and receiving information.</p>",
      preamble_fallback: null,
      preamble_accountable: "Legal",
      preamble_approval: true,
      preamble_text__vs: null,
      preamble_approval__vs: null,
      preamble_comment: null,
      preamble_comment__vs: null,
      preamble_compare: null,
      preamble_timestamp: "2020-12-02T10:30:00Z",
      preamble_updated: false
    },
    {
      preamble_index: 3,
      preamble_con_index: 6,
      preamble_sec_index: 100,
      preamble_point: "A.3",
      preamble_order: 3,
      preamble_type: "whereas",
      preamble_text: "<p>WHEREAS, the PARTIES want to explore the PROPOSED TRANSACTION.</p>",
      preamble_status: "final",
      preamble_negotiable: false,
      preamble_short: "Purpose of disclosure",
      preamble_info: "References the commercial purpose for which information is disclosed",
      preamble_meta: "<p>Transaction exploration purpose</p>",
      preamble_playbook: "<p>Establishes the legitimate business purpose for disclosure. Important for limiting use of confidential information to authorized purposes only. Helps defend against claims that information can be used for competitive purposes or general business development.</p>",
      preamble_fallback: null,
      preamble_accountable: "Legal",
      preamble_approval: true,
      preamble_text__vs: null,
      preamble_approval__vs: null,
      preamble_comment: null,
      preamble_comment__vs: null,
      preamble_compare: null,
      preamble_timestamp: "2020-12-02T10:30:00Z",
      preamble_updated: false
    },
    {
      preamble_index: 4,
      preamble_con_index: 6,
      preamble_sec_index: 100,
      preamble_point: "A.4",
      preamble_order: 4,
      preamble_type: "whereas",
      preamble_text: "<p>WHEREAS, the PARTIES expect that to assist each PARTY in determining whether to proceed with the PROPOSED TRANSACTION, each PARTY will provide the other with CONFIDENTIAL INFORMATION.</p>",
      preamble_status: "final",
      preamble_negotiable: false,
      preamble_short: "Transaction evaluation purpose",
      preamble_info: "Clarifies that disclosure is for transaction assessment purposes",
      preamble_meta: "<p>Due diligence context</p>",
      preamble_playbook: "<p>Reinforces limited purpose use restriction. Helps defend against claims that information can be used for competitive purposes or general business development. Creates clear boundary around permissible uses of disclosed information.</p>",
      preamble_fallback: null,
      preamble_accountable: "Legal",
      preamble_approval: true,
      preamble_text__vs: null,
      preamble_approval__vs: null,
      preamble_comment: null,
      preamble_comment__vs: null,
      preamble_compare: null,
      preamble_timestamp: "2020-12-02T10:30:00Z",
      preamble_updated: false
    }
  ],

  // Definitions
  definitions: [
    {
      def_index: 200,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.1",
      def_order: 1,
      def_key: "AFFILIATE",
      def_value: "<p>\"AFFILIATE\" means an entity that, directly or indirectly, CONTROLS, is CONTROLLED by, or is under common CONTROL with a PARTY to this AGREEMENT, but only for so long as such control exists.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Corporate group relationship definition",
      def_info: "Defines related entities within corporate structure",
      def_meta: "<p>Corporate affiliation scope</p>",
      def_playbook: "<p>Standard definition for corporate groups. Important for determining who can receive confidential information. Consider whether to limit affiliate access or require separate NDAs for affiliates in high-risk jurisdictions. The 'for so long as such control exists' language is critical - prevents former affiliates from retaining access rights.</p>",
      def_fallback: "Subsidiary or parent company as determined by legal ownership structure",
      def_accountable: "Legal, Finance",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 201,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.2",
      def_order: 2,
      def_key: "AGREEMENT",
      def_value: "<p>\"AGREEMENT\" has the meaning defined in the RECITALS.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Self-reference to this NDA",
      def_info: "Cross-reference to this Non-Disclosure Agreement",
      def_meta: "<p>Document self-reference</p>",
      def_playbook: "<p>Standard cross-reference clause. No negotiation typically required. Establishes circular reference to the preamble for definitional purposes.</p>",
      def_fallback: "This Non-Disclosure Agreement",
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 202,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.3",
      def_order: 3,
      def_key: "AUTHORIZED ACCESS",
      def_value: "<p>\"AUTHORIZED ACCESS\" means access to Confidential Information by those employees, consultants, and advisors of the Recipient who have a legitimate business need to know and who are bound by confidentiality obligations no less restrictive than those contained in this Agreement.</p>",
      def_status: "placeholder",
      def_negotiable: true,
      def_short: "Permitted recipient scope",
      def_info: "Defines who within recipient organization can access confidential information",
      def_meta: "<p>Access control definition</p>",
      def_playbook: "<p>Define the scope of authorized personnel carefully. Consider whether contractors, advisors, and service providers should be included. May need to specify requirements for background checks or security clearances for highly sensitive information. Ensure flow-down confidentiality obligations are enforceable. The 'need to know' standard is important but subjective - consider whether to define more precisely.</p>",
      def_fallback: "Access limited to employees with direct business responsibility for the proposed transaction",
      def_accountable: "Legal, Security, Human Resources",
      def_approval: false,
      def_value__vs: "<p>\"AUTHORIZED ACCESS\" means access to Confidential Information by those employees, contractors, consultants, legal advisors, and financial advisors of the Recipient who have a legitimate business need to know, who are bound by confidentiality obligations no less restrictive than those contained in this Agreement, and who have been approved in writing by the Discloser.</p>",
      def_approval__vs: false,
      def_comment: null,
      def_comment__vs: "Version 2 adds contractors and requires Discloser approval - may be too restrictive for operational efficiency",
      def_compare: "Version 2 expands authorized recipients but adds approval requirement.",
      def_timestamp: null,
      def_updated: false
    },
    {
      def_index: 203,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.4",
      def_order: 4,
      def_key: "CONFIDENTIAL INFORMATION",
      def_value: "<p>\"CONFIDENTIAL INFORMATION\" means information relating to the DISCLOSER and its business, its AFFILIATES, its shareholders, its customers, and its suppliers that is disclosed to the RECIPIENT during the DISCLOSURE PERIOD.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Scope of protected information",
      def_info: "Broad definition covering business-critical information",
      def_meta: "<p>Information protection scope</p>",
      def_playbook: "<p>Broad definition provides maximum protection for Discloser. Recipients may push back requesting narrower scope or requirement that information be marked 'confidential.' Balance protection needs with practicality of marking all confidential disclosures. Consider whether oral disclosures should be included (best practice: require written confirmation within X days). Should include standard exceptions: publicly available information, independently developed information, information already known without restriction, information received from third party without confidentiality obligation.</p>",
      def_fallback: "Information disclosed in writing and marked as confidential",
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 204,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.5",
      def_order: 5,
      def_key: "CONTROL",
      def_value: "<p>\"CONTROL\" means the possession, directly or indirectly, of the power to direct or cause the direction of the management or policies of an entity, whether through ownership of voting securities, by contract, or otherwise.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Corporate control threshold",
      def_info: "Establishes ownership and management control thresholds",
      def_meta: "<p>Control definition for affiliates</p>",
      def_playbook: "<p>Standard definition for determining affiliate relationships and change of control triggers. Consider specifying percentage thresholds (e.g., 50% voting rights) if more certainty is needed. The 'by contract or otherwise' language is important as it captures management control without equity ownership.</p>",
      def_fallback: "Direct or indirect ownership of more than 50% of voting rights",
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 205,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.6",
      def_order: 6,
      def_key: "DISCLOSURE PERIOD",
      def_value: "<p>\"DISCLOSURE PERIOD\" means the period commencing on the Effective Date and ending on the earlier of (i) the second anniversary of the Effective Date, (ii) the termination of the RELATIONSHIP AGREEMENT, or (iii) such other date as the PARTIES may mutually agree in writing.</p>",
      def_status: "final",
      def_negotiable: true,
      def_short: "Information sharing timeframe",
      def_info: "Period during which confidential information may be disclosed",
      def_meta: "<p>Disclosure window definition</p>",
      def_playbook: "<p>Balance adequate evaluation time against limiting exposure duration. Two years is standard for M&A due diligence. Shorter periods (6-12 months) common for vendor evaluations. Consider automatic extension provisions if transaction discussions continue. Important: this defines when disclosure CAN occur, not how long confidentiality obligations last (typically much longer - 3-5 years post-disclosure).</p>",
      def_fallback: "One year from the date of first disclosure",
      def_accountable: "Legal, Business Development",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 206,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.7",
      def_order: 7,
      def_key: "DISCLOSER",
      def_value: "<p>\"DISCLOSER\" means the PARTY that is disclosing CONFIDENTIAL INFORMATION to the RECIPIENT pursuant to this AGREEMENT.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Information provider",
      def_info: "Party revealing confidential information",
      def_meta: "<p>Disclosing party role</p>",
      def_playbook: "<p>Standard definition. No negotiation required. In bilateral NDAs, each party can be both Discloser and Recipient at different times.</p>",
      def_fallback: null,
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 207,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.8",
      def_order: 8,
      def_key: "EFFECTIVE DATE",
      def_value: "<p>\"EFFECTIVE DATE\" means the date first written above.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Agreement start date",
      def_info: "Date when agreement becomes effective",
      def_meta: "<p>Commencement date</p>",
      def_playbook: "<p>Standard definition. Ensure date is filled in before execution. Some parties prefer 'date of last signature' to avoid timing issues. Consider whether agreement should be effective retroactively if parties have already begun sharing information.</p>",
      def_fallback: "Date of signature by both parties",
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    },
    {
      def_index: 208,
      def_con_index: 6,
      def_sec_index: 101,
      def_point: "B.9",
      def_order: 9,
      def_key: "RECIPIENT",
      def_value: "<p>\"RECIPIENT\" means the PARTY receiving CONFIDENTIAL INFORMATION from the DISCLOSER pursuant to this AGREEMENT.</p>",
      def_status: "final",
      def_negotiable: false,
      def_short: "Information receiver",
      def_info: "Party receiving confidential information",
      def_meta: "<p>Receiving party role</p>",
      def_playbook: "<p>Standard definition. No negotiation required. In bilateral NDAs, each party can be both Discloser and Recipient at different times.</p>",
      def_fallback: null,
      def_accountable: "Legal",
      def_approval: true,
      def_value__vs: null,
      def_approval__vs: null,
      def_comment: null,
      def_comment__vs: null,
      def_compare: null,
      def_timestamp: "2020-12-02T10:30:00Z",
      def_updated: false
    }
  ],

  // Main Clauses - EXACTLY 10 CLAUSES
  clauses: [
    // CLAUSE 1: Duties and Obligations (with 10 sub-clauses)
    {
      cla_index: 300,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Duties and Obligations",
      cla_point: "1",
      cla_order: 1,
      cla_text: "<p>Each RECIPIENT shall protect and maintain the confidentiality of all CONFIDENTIAL INFORMATION received from the DISCLOSER, using the same degree of care that it uses to protect its own confidential information, but in no event less than reasonable care. The RECIPIENT agrees to use the CONFIDENTIAL INFORMATION solely for the purpose of evaluating and negotiating the PROPOSED TRANSACTION and shall not use such information for any other purpose whatsoever without the prior written consent of the DISCLOSER.</p>",
      cla_negotiable: false,
      cla_short: "Standard of care for confidentiality",
      cla_info: "Establishes fundamental obligation to protect confidential information with reasonable care standard",
      cla_meta: "<p>Core confidentiality obligation</p>",
      cla_playbook: "<p>This is the heart of the NDA. 'Reasonable care' standard is generally market. Some recipients push for 'same care as own information' only (removing 'reasonable care' floor), which is risky if recipient has lax internal practices. Disclosers may request 'best efforts' or 'highest degree of care' but this is often commercially unreasonable. The limited purpose language is critical - prevents use of information for competitive intelligence or general business purposes.</p>",
      cla_fallback: "Use best efforts to maintain confidentiality",
      cla_accountable: "Legal, Compliance, Operations",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 301,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Maintaining Confidentiality",
      cla_point: "1.1",
      cla_order: 2,
      cla_text: "<p>The RECIPIENT shall limit disclosure of CONFIDENTIAL INFORMATION to its employees, consultants, and professional advisors who have a legitimate business need to know and who are bound by written confidentiality obligations no less restrictive than those contained in this AGREEMENT. The RECIPIENT shall ensure that such individuals are informed of the confidential nature of the information and shall remain responsible for their compliance with the terms of this AGREEMENT.</p>",
      cla_negotiable: true,
      cla_short: "Authorized disclosure scope",
      cla_info: "Defines who within recipient organization can access confidential information and recipient's responsibility for their compliance",
      cla_meta: "<p>Internal disclosure controls</p>",
      cla_playbook: "<p>Key negotiation point. Recipient wants flexibility to share with broad range of advisors and service providers. Discloser wants tight control. Consider whether to expand explicitly to 'auditors,' 'financing sources,' 'potential acquirers' etc. 'Need to know' language is critical - prevents unnecessary distribution. Ensure recipient remains liable for breaches by third parties they disclose to. The 'no less restrictive' language ensures flow-down protection.</p>",
      cla_fallback: "Limit disclosure to executive management only",
      cla_accountable: "Legal, Human Resources, Compliance",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 302,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Precautions against Unauthorized Disclosure or Use",
      cla_point: "1.2",
      cla_order: 3,
      cla_text: "<p>The RECIPIENT shall implement and maintain reasonable technical, administrative, and physical safeguards designed to prevent unauthorized access to, use of, or disclosure of CONFIDENTIAL INFORMATION. These safeguards shall include, at a minimum: (a) restricting access to CONFIDENTIAL INFORMATION to authorized personnel; (b) maintaining secure storage facilities with appropriate access controls; (c) utilizing encryption for electronic transmission of sensitive data; and (d) maintaining a log of all disclosures of CONFIDENTIAL INFORMATION to third parties. The RECIPIENT shall promptly notify the DISCLOSER of any unauthorized access, use, or disclosure of which it becomes aware.</p>",
      cla_negotiable: true,
      cla_short: "Security measures required",
      cla_info: "Specifies minimum security controls recipient must implement",
      cla_meta: "<p>Technical safeguards requirements</p>",
      cla_playbook: "<p>Level of specificity depends on information sensitivity. For highly sensitive data (personal information, trade secrets, financial data), consider requiring specific standards like ISO 27001, SOC 2, or industry-specific frameworks. Be realistic about what recipient can implement. Encryption requirements for transmission are increasingly standard. Disclosure logs useful for audit but may be burdensome - consider whether truly necessary. Recipients often push back on specific technical requirements as overly prescriptive.</p>",
      cla_fallback: "Use commercially reasonable security measures",
      cla_accountable: "Legal, Information Security, Operations",
      cla_approval: true,
      cla_text__vs: "<p>The RECIPIENT shall implement and maintain security measures consistent with industry standards including ISO 27001 certification or equivalent to prevent unauthorized access to, use of, or disclosure of CONFIDENTIAL INFORMATION. The RECIPIENT shall promptly (within 24 hours) notify the DISCLOSER of any unauthorized access, use, or disclosure of which it becomes aware.</p>",
      cla_approval__vs: false,
      cla_comment: null,
      cla_comment__vs: "ISO 27001 requirement may be too onerous; 24-hour notification may be unrealistic",
      cla_compare: "Version 2 requires ISO 27001 and faster breach notification.",
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 303,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Notifying the DISCLOSER of Unauthorized Disclosure or Use",
      cla_point: "1.3",
      cla_order: 4,
      cla_text: "<p>In the event that the RECIPIENT becomes aware of any unauthorized access to, use of, or disclosure of CONFIDENTIAL INFORMATION, the RECIPIENT shall immediately (and in no event later than five (5) business days) notify the DISCLOSER in writing of such occurrence. The notification shall include details of: (i) the nature and scope of the unauthorized access, use, or disclosure; (ii) the CONFIDENTIAL INFORMATION affected; (iii) the parties involved or likely to be involved; (iv) the steps the RECIPIENT is taking to prevent further unauthorized use or disclosure; and (v) the steps the RECIPIENT will take to mitigate any harm resulting from such unauthorized access, use, or disclosure.</p>",
      cla_negotiable: true,
      cla_short: "Breach notification protocol",
      cla_info: "Timeline and content requirements for reporting security breaches",
      cla_meta: "<p>Incident response obligations</p>",
      cla_playbook: "<p>Notification timeframe is key negotiation point. Immediate notification (24-48 hours) may be unrealistic given need to investigate. 5 business days is reasonable middle ground. Balance prompt notification with time to gather accurate information. Consider whether recipient must bear costs of remediation (forensic investigation, notification costs, credit monitoring if personal data involved). Specify who at Discloser should be notified. Consider escalation procedures for serious breaches.</p>",
      cla_fallback: "Notify within 10 business days",
      cla_accountable: "Legal, Compliance, Information Security",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 304,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Non-Disclosure of Agreement",
      cla_point: "1.4",
      cla_order: 5,
      cla_text: "<p>Except as required by law or regulatory authority, each PARTY shall maintain the confidentiality of the existence and the terms of this AGREEMENT. Neither PARTY shall make any announcement, press release, or other public disclosure regarding this AGREEMENT without the prior written consent of the other PARTY, except as may be required by applicable law or regulation or by the rules of any stock exchange on which the PARTY's securities are listed. If a disclosure is required by law or regulation, the disclosing PARTY shall, to the extent legally permitted, provide the other PARTY with prompt notice to allow the other PARTY an opportunity to seek protective measures.</p>",
      cla_negotiable: true,
      cla_short: "Confidentiality of NDA itself",
      cla_info: "Prevents disclosure of agreement existence and terms",
      cla_meta: "<p>Meta-confidentiality provision</p>",
      cla_playbook: "<p>Important for preventing market speculation about potential transactions. Consider carve-outs for disclosures to: (1) board of directors, (2) legal counsel, (3) auditors, (4) potential financing sources. Public companies may need more flexibility for securities law compliance (e.g., materiality disclosures). Determine whether mutual consent is required for legally mandated disclosures or if notice alone is sufficient. Some jurisdictions may require disclosure in litigation or regulatory proceedings.</p>",
      cla_fallback: "Complete confidentiality regarding agreement existence",
      cla_accountable: "Legal, Communications, Compliance",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 305,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "No Reverse Engineering",
      cla_point: "1.5",
      cla_order: 6,
      cla_text: "<p>The RECIPIENT shall not, without the prior written consent of the DISCLOSER: (a) reverse engineer, disassemble, or decompile any CONFIDENTIAL INFORMATION that is in tangible or electronic form; (b) attempt to derive the underlying process, methodology, or source code of any CONFIDENTIAL INFORMATION; or (c) conduct any analysis to discover the underlying principles or structure of any CONFIDENTIAL INFORMATION. The RECIPIENT shall ensure that its employees, consultants, and advisors comply with this restriction and shall remain responsible for any violations thereof.</p>",
      cla_negotiable: true,
      cla_short: "Prohibition on reverse engineering",
      cla_info: "Prevents recipient from deconstructing confidential information to derive underlying secrets",
      cla_meta: "<p>Reverse engineering restrictions</p>",
      cla_playbook: "<p>Critical for technology and product disclosures. Consider scope carefully - does prohibition extend to independently developed solutions based on concepts learned? Some jurisdictions limit enforceability of reverse engineering prohibitions (e.g., EU software directive allows reverse engineering for interoperability). Include explicit prohibition on using disclosed information to develop competing products. Consider whether interoperability exception is needed. May be unenforceable in certain contexts (software, pharmaceuticals).</p>",
      cla_fallback: "Prohibition applies only to deliberate reverse engineering efforts",
      cla_accountable: "Legal, Technical Operations, Research & Development",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 306,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Non-Disclosure to Third Parties",
      cla_point: "1.6",
      cla_order: 7,
      cla_text: "<p>The RECIPIENT shall not disclose, transfer, or make available any CONFIDENTIAL INFORMATION to any third party, including without limitation to any competitor of the DISCLOSER, without the prior written consent of the DISCLOSER. This restriction shall apply to all forms of CONFIDENTIAL INFORMATION, including electronic, written, oral, or visual formats. The RECIPIENT acknowledges that any breach of this restriction would cause irreparable harm to the DISCLOSER for which monetary damages would be an inadequate remedy, and the DISCLOSER shall be entitled to seek injunctive relief in addition to all other available remedies.</p>",
      cla_negotiable: true,
      cla_short: "Third-party disclosure prohibition",
      cla_info: "Prevents disclosure to external parties, especially competitors",
      cla_meta: "<p>External disclosure restrictions</p>",
      cla_playbook: "<p>Broad prohibition subject to carve-outs for advisors, financing sources, etc. (typically addressed in earlier clauses). Competitor prohibition is critical - ensure 'competitor' is well-defined or objectively determinable. Irreparable harm language supports requests for injunctive relief and may help overcome procedural hurdles in litigation. Consider whether prior written consent requirement is workable or if certain categories should be pre-approved. Recipients may negotiate for email consent to be sufficient vs. formal written documents.</p>",
      cla_fallback: "Disclosure permitted to advisors with confidentiality obligations",
      cla_accountable: "Legal, Compliance",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 307,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Accuracy of Confidential Information",
      cla_point: "1.7",
      cla_order: 8,
      cla_text: "<p>The DISCLOSER warrants that to the best of its knowledge, the CONFIDENTIAL INFORMATION provided is accurate, complete, and not misleading as of the date of disclosure. However, the DISCLOSER does not make any other representation or warranty with respect to the CONFIDENTIAL INFORMATION, including without limitation any warranty of merchantability, fitness for a particular purpose, or non-infringement. The RECIPIENT acknowledges that it is responsible for independently verifying the accuracy and completeness of any CONFIDENTIAL INFORMATION and shall not rely solely upon such information in making any business decisions.</p>",
      cla_negotiable: true,
      cla_short: "Information accuracy disclaimer",
      cla_info: "Limited warranty regarding accuracy of disclosed information",
      cla_meta: "<p>Warranty and disclaimer provisions</p>",
      cla_playbook: "<p>Discloser wants to minimize representations about information accuracy to avoid liability. Recipient wants some assurance information is reliable. 'Best of knowledge' qualifier limits warranty to information discloser actually knows. Consider time-based limitations (e.g., accuracy as of specific date only). Disclaimer of implied warranties is standard. If recipient is making significant investment decisions, may negotiate for stronger representations or due diligence rights. This becomes more important in M&A contexts where reliance is material.</p>",
      cla_fallback: "DISCLOSER makes no representations regarding CONFIDENTIAL INFORMATION",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 308,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Handling of Restricted Information",
      cla_point: "1.8",
      cla_order: 9,
      cla_text: "<p>In addition to the general confidentiality obligations set forth in this AGREEMENT, the RECIPIENT shall not disclose any CONFIDENTIAL INFORMATION that is specifically marked as 'RESTRICTED' or 'HIGHLY CONFIDENTIAL' to any person outside of its organization without the explicit prior written consent of the DISCLOSER. The RECIPIENT shall implement special handling procedures for such restricted information, including segregated storage, limited access, and audit trails. Any violations of these enhanced protections shall be subject to immediate remedial action and may constitute grounds for termination of this AGREEMENT.</p>",
      cla_negotiable: true,
      cla_short: "Enhanced protection for sensitive data",
      cla_info: "Additional safeguards for most sensitive confidential information",
      cla_meta: "<p>Tiered confidentiality framework</p>",
      cla_playbook: "<p>Creates two-tier confidentiality system for varying sensitivity levels. Useful when some information is particularly sensitive (e.g., unreleased financials, M&A targets, trade secrets). Ensure marking requirements are clear and consistently applied. Consider whether this adds unnecessary complexity or provides meaningful additional protection. May want to specify different retention/return obligations for restricted information. Recipients may resist this as administratively burdensome. Consider whether to specify exactly what 'special handling procedures' means.</p>",
      cla_fallback: "All CONFIDENTIAL INFORMATION is treated equally",
      cla_accountable: "Legal, Compliance, Information Security",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 309,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Proprietary Notices",
      cla_point: "1.9",
      cla_order: 10,
      cla_text: "<p>All CONFIDENTIAL INFORMATION provided in written or electronic form shall be marked with appropriate proprietary notices (e.g., 'CONFIDENTIAL,' 'PROPRIETARY,' or 'FOR LIMITED DISTRIBUTION'). The RECIPIENT shall preserve all such proprietary notices and markings on any copies made of the CONFIDENTIAL INFORMATION. Where CONFIDENTIAL INFORMATION is disclosed orally, the DISCLOSER shall provide written confirmation of the confidential nature of such disclosure within five (5) business days. The RECIPIENT shall use commercially reasonable efforts to ensure that the confidential nature of all CONFIDENTIAL INFORMATION is respected and maintained throughout its organization.</p>",
      cla_negotiable: true,
      cla_short: "Confidentiality marking requirements",
      cla_info: "Procedure for identifying and preserving confidential designations",
      cla_meta: "<p>Marking and notice procedures</p>",
      cla_playbook: "<p>Marking requirements help recipient identify what's confidential but can be administratively burdensome for discloser. Consider whether failure to mark waives confidentiality (dangerous for discloser) or whether unmarked information receives benefit of doubt. Five business days for oral disclosure confirmation is reasonable. Some recipients request that only marked information is confidential - resist this if possible as it's easy to overlook marking in practice. Balance: Discloser wants broad protection regardless of marking; Recipient wants clear notice of what's actually confidential.</p>",
      cla_fallback: "Proprietary notices are recommended but not required",
      cla_accountable: "Legal, Operations",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },
    {
      cla_index: 310,
      cla_sec_index: 103,
      cla_con_index: 6,
      cla_header: "Return of Confidential Information",
      cla_point: "1.10",
      cla_order: 11,
      cla_text: "<p>Upon the written request of the DISCLOSER, or upon the earlier of (i) the termination of this AGREEMENT or (ii) the termination of the RELATIONSHIP, the RECIPIENT shall promptly (and in no event later than thirty (30) days) return to the DISCLOSER, or at the DISCLOSER's election, securely destroy all CONFIDENTIAL INFORMATION in its possession or control, including all copies, summaries, or derivative works, except that the RECIPIENT may retain one archival copy for legal compliance purposes, provided that such retained copy shall remain subject to all confidentiality obligations hereunder. The RECIPIENT shall provide written certification of such return or destruction, including certification that all electronic copies have been securely deleted or destroyed.</p>",
      cla_negotiable: true,
      cla_short: "Information return/destruction protocol",
      cla_info: "Procedures for returning or destroying confidential information at relationship end",
      cla_meta: "<p>Post-termination obligations</p>",
      cla_playbook: "<p>Return/destruction obligation is standard but increasingly difficult in digital age (emails, backups, cloud storage). Thirty days is reasonable timeframe. Archival copy exception is important for legal/regulatory compliance and litigation readiness - ensure it remains subject to confidentiality obligations. Certification requirement provides comfort but consider enforceability concerns. May need specific provisions for electronic data (secure deletion standards, backup tape handling). Recipients often request exception for automatic backup systems that can't be easily purged.</p>",
      cla_fallback: "Best efforts to return or destroy CONFIDENTIAL INFORMATION",
      cla_accountable: "Legal, Information Security, Operations",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 2: Assignment
    {
      cla_index: 311,
      cla_sec_index: 104,
      cla_con_index: 6,
      cla_header: "Assignment of Rights or Obligations",
      cla_point: "2",
      cla_order: 1,
      cla_text: "<p>NEITHER PARTY may assign its rights or delegate its obligations under this AGREEMENT, in whole or in part, without the prior written consent of the other PARTY (which consent shall not be unreasonably withheld). Any attempted assignment or delegation in violation of this provision shall be void and of no effect.</p>",
      cla_negotiable: true,
      cla_short: "Assignment restrictions",
      cla_info: "Controls when parties can transfer agreement rights/obligations",
      cla_meta: "<p>Assignment and succession provisions</p>",
      cla_playbook: "<p>Standard prohibition on assignment protects parties from being forced into relationships with unknown third parties. Consider carve-outs for: (1) assignments to affiliates, (2) assignments to successor entities in merger/acquisition, (3) assignments to financing sources as collateral. 'Not unreasonably withheld' standard provides flexibility while maintaining control. Some parties request that affiliate assignments don't require consent. Consider whether assignment should trigger termination right rather than requiring consent. In M&A, this can become contentious if acquirer is a competitor.</p>",
      cla_fallback: "No assignment permitted without explicit written consent",
      cla_accountable: "Legal, Business Development",
      cla_approval: true,
      cla_text__vs: "<p>NEITHER PARTY may assign its rights or delegate its obligations under this AGREEMENT without the prior written consent of the other PARTY, except that either PARTY may assign this AGREEMENT to an AFFILIATE or to a successor entity in connection with a merger, acquisition, or sale of substantially all of its assets without consent, provided that the assignee agrees in writing to be bound by all terms of this AGREEMENT.</p>",
      cla_approval__vs: true,
      cla_comment: null,
      cla_comment__vs: "Version 2 adds carve-outs for common business transactions",
      cla_compare: "Version 2 permits assignment to affiliates and successors without consent.",
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 3: Severability
    {
      cla_index: 312,
      cla_sec_index: 105,
      cla_con_index: 6,
      cla_header: "Severability",
      cla_point: "3",
      cla_order: 1,
      cla_text: "<p>The invalidity or unenforceability of any provision of this AGREEMENT shall not affect the validity or enforceability of any other provision of this AGREEMENT. If any provision is found to be invalid or unenforceable, such provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving the intent of the parties.</p>",
      cla_negotiable: false,
      cla_short: "Invalid clause preservation",
      cla_info: "Ensures remaining provisions survive if one clause is found unenforceable",
      cla_meta: "<p>Severability protection</p>",
      cla_playbook: "<p>Standard 'blue pencil' provision allowing court to modify rather than void entire agreement if provision is overbroad. No negotiation typically required. Particularly important for restrictive covenants which may be subject to reasonableness review by courts. Prevents one unenforceable term from invalidating entire agreement. Some jurisdictions more willing to 'blue pencil' than others.</p>",
      cla_fallback: "Entire agreement is void if any provision is invalid",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 4: Change of Control
    {
      cla_index: 313,
      cla_sec_index: 106,
      cla_con_index: 6,
      cla_header: "Change of Control",
      cla_point: "4",
      cla_order: 1,
      cla_text: "<p>Either PARTY shall have the right, without prejudice to its other rights or remedies, to terminate this AGREEMENT by three (3) months' written notice to the other PARTY, if there is a change of control of the other PARTY. For purposes of this provision, 'change of control' means: (i) the sale of substantially all of the assets of a PARTY; (ii) a merger or consolidation in which a PARTY is not the surviving entity; or (iii) the acquisition by any person or group of more than fifty percent (50%) of the voting equity of a PARTY.</p>",
      cla_negotiable: true,
      cla_short: "Termination right upon ownership change",
      cla_info: "Allows termination if other party undergoes change in control",
      cla_meta: "<p>Change of control protections</p>",
      cla_playbook: "<p>Protects parties from being bound to unknown new owners. Three months' notice is reasonable. Consider whether: (1) definition of 'change of control' is appropriate (50% threshold is standard), (2) certain types of transactions should be excluded (e.g., IPO, internal restructuring, private equity recapitalization), (3) termination should be automatic vs. optional, (4) any financial consequences should attach. Some parties negotiate for assignment rights to new owner rather than termination. Particularly important if counterparty might be acquired by competitor.</p>",
      cla_fallback: "Immediate termination upon change of control",
      cla_accountable: "Legal, Business Development",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 5: Term and Termination
    {
      cla_index: 314,
      cla_sec_index: 107,
      cla_con_index: 6,
      cla_header: "Term and Termination",
      cla_point: "5",
      cla_order: 1,
      cla_text: "<p>This AGREEMENT shall commence on the Effective Date and shall continue for a period of three (3) years unless earlier terminated in accordance with the provisions hereof. Either PARTY may terminate this AGREEMENT for cause upon thirty (30) days' written notice if the other PARTY materially breaches any provision of this AGREEMENT and fails to cure such breach within thirty (30) days after receiving written notice thereof. Upon termination of this AGREEMENT for any reason, all obligations of the RECIPIENT with respect to CONFIDENTIAL INFORMATION shall survive in accordance with the terms of this AGREEMENT.</p>",
      cla_negotiable: true,
      cla_short: "Agreement duration and termination conditions",
      cla_info: "Defines how long agreement lasts and conditions for early termination",
      cla_meta: "<p>Term and termination framework</p>",
      cla_playbook: "<p>Three-year term is standard for NDAs, though length varies with transaction type (shorter for vendor evaluations, longer for technology partnerships). Consider: (1) whether agreement should auto-renew, (2) appropriate cure period for breaches (30 days is reasonable for most breaches; some breaches like unauthorized disclosure may warrant immediate termination), (3) what obligations survive termination (confidentiality should definitely survive; consider whether other terms like return/destruction, remedies, etc. should also survive), (4) whether convenience termination should be permitted. Survival of confidentiality obligations post-termination is critical.</p>",
      cla_fallback: "Agreement terminates automatically at end of stated term unless renewed",
      cla_accountable: "Legal",
      cla_approval: false,
      cla_text__vs: "<p>This AGREEMENT shall commence on the Effective Date and shall continue for a period of five (5) years unless earlier terminated. Either PARTY may terminate this AGREEMENT for convenience upon ninety (90) days' written notice. Either PARTY may terminate immediately for material breach without cure period. Confidentiality obligations survive for five (5) years post-termination.</p>",
      cla_approval__vs: false,
      cla_comment: null,
      cla_comment__vs: "Five-year term may be too long; immediate termination without cure is too harsh; consider whether convenience termination undermines confidentiality commitment",
      cla_compare: "Version 2 extends term, adds convenience termination, removes cure period, and specifies post-termination survival period.",
      cla_timestamp: null,
      cla_updated: false
    },

    // CLAUSE 6: Entire Agreement
    {
      cla_index: 315,
      cla_sec_index: 108,
      cla_con_index: 6,
      cla_header: "Entire Agreement",
      cla_point: "6",
      cla_order: 1,
      cla_text: "<p>This AGREEMENT, together with the RELATIONSHIP AGREEMENT, constitutes the entire agreement between the PARTIES with respect to the subject matter hereof and supersedes all prior and contemporaneous negotiations, representations, and agreements, whether written or oral. No modification, amendment, or waiver of any provision of this AGREEMENT shall be effective unless in writing and signed by both PARTIES.</p>",
      cla_negotiable: false,
      cla_short: "Complete agreement integration",
      cla_info: "Confirms this document represents complete understanding between parties",
      cla_meta: "<p>Integration and amendment provisions</p>",
      cla_playbook: "<p>Standard integration clause preventing parties from relying on prior statements or side agreements. Important to list all related agreements that should be read together (here, the RELATIONSHIP AGREEMENT). Requirement that modifications be in writing and signed prevents informal amendments. Standard provision, typically non-negotiable. Ensure this actually reflects the complete agreement - if other documents are part of the deal, reference them explicitly. Protects against claims based on pre-contract negotiations or representations.</p>",
      cla_fallback: "Prior agreements remain in effect",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 7: Governing Law
    {
      cla_index: 316,
      cla_sec_index: 109,
      cla_con_index: 6,
      cla_header: "Governing Law and Jurisdiction",
      cla_point: "7",
      cla_order: 1,
      cla_text: "<p>This AGREEMENT shall be governed by and construed in accordance with the laws of the Federal Republic of Germany (without regard to its conflicts of law principles). Each PARTY irrevocably submits to the exclusive jurisdiction of the courts located in Munich, Germany for the resolution of any disputes arising out of or related to this AGREEMENT.</p>",
      cla_negotiable: true,
      cla_short: "Applicable law and court selection",
      cla_info: "Determines which country's laws apply and where disputes will be resolved",
      cla_meta: "<p>Choice of law and forum</p>",
      cla_playbook: "<p>Choice of law is often contentious, with each party preferring its home jurisdiction. Munich (Germany) makes sense here given both parties are German. Consider: (1) whether conflict of laws exclusion is appropriate (generally yes, to avoid circular application of another jurisdiction's laws), (2) whether exclusive jurisdiction is acceptable vs. non-exclusive (exclusive prevents forum shopping but may be inconvenient), (3) whether arbitration would be preferable to litigation (faster, more confidential, more expensive). For international deals, consider neutral jurisdiction or arbitration (ICC, LCIA, etc.).</p>",
      cla_fallback: "German law applies; Munich courts have jurisdiction",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 8: No License
    {
      cla_index: 317,
      cla_sec_index: 110,
      cla_con_index: 6,
      cla_header: "No License",
      cla_point: "8",
      cla_order: 1,
      cla_text: "<p>No license or other intellectual property right is granted by this AGREEMENT. The disclosure of CONFIDENTIAL INFORMATION does not grant the RECIPIENT any rights to such information except as expressly set forth herein. All intellectual property rights in the CONFIDENTIAL INFORMATION shall remain the exclusive property of the DISCLOSER or its licensors.</p>",
      cla_negotiable: false,
      cla_short: "No IP rights transferred",
      cla_info: "Clarifies disclosure doesn't grant ownership or license rights",
      cla_meta: "<p>IP ownership preservation</p>",
      cla_playbook: "<p>Critical provision clarifying that disclosure is purely for evaluation, not a license to use or exploit the information. Prevents implied license arguments. Particularly important for technology, software, patents, and other IP-heavy disclosures. Generally non-negotiable. If parties do intend to grant license rights, those should be in a separate license agreement with appropriate consideration and terms. This prevents 'we had access to your IP so we can use it' arguments later.</p>",
      cla_fallback: "RECIPIENT receives limited license only for evaluation purposes",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 9: No Obligation to Proceed
    {
      cla_index: 318,
      cla_sec_index: 111,
      cla_con_index: 6,
      cla_header: "No Obligation to Proceed",
      cla_point: "9",
      cla_order: 1,
      cla_text: "<p>The disclosure of CONFIDENTIAL INFORMATION does not constitute any commitment or obligation on the part of either PARTY to proceed with the PROPOSED TRANSACTION. Either PARTY may withdraw from discussions and negotiations at any time without liability, provided that confidentiality obligations shall survive any such withdrawal.</p>",
      cla_negotiable: false,
      cla_short: "No binding commitment created",
      cla_info: "Confirms parties can walk away without liability",
      cla_meta: "<p>Non-binding negotiation status</p>",
      cla_playbook: "<p>Essential provision making clear that NDA doesn't obligate parties to consummate any transaction. Preserves freedom to walk away from negotiations. Important for preventing promissory estoppel or similar claims. Survival of confidentiality obligations despite withdrawal is critical - protects discloser even if deal doesn't proceed. Generally non-negotiable. If parties do intend binding commitment, that should be in a separate letter of intent or term sheet with appropriate conditions and consideration. Prevents 'you led me on' claims.</p>",
      cla_fallback: "Each party retains full discretion to proceed or decline",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: null,
      cla_approval__vs: null,
      cla_comment: null,
      cla_comment__vs: null,
      cla_compare: null,
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    },

    // CLAUSE 10: Remedies
    {
      cla_index: 319,
      cla_sec_index: 112,
      cla_con_index: 6,
      cla_header: "Remedies",
      cla_point: "10",
      cla_order: 1,
      cla_text: "<p>The RECIPIENT acknowledges that any breach of this AGREEMENT would cause irreparable harm to the DISCLOSER for which monetary damages would be an inadequate remedy. In addition to all other remedies available at law or in equity, the DISCLOSER shall be entitled to seek specific performance and injunctive relief to prevent any breach or threatened breach of this AGREEMENT without the necessity of posting a bond. The right to seek injunctive relief shall not prevent the DISCLOSER from seeking or obtaining other relief, including monetary damages.</p>",
      cla_negotiable: true,
      cla_short: "Equitable and legal remedies available",
      cla_info: "Authorizes injunctions and other extraordinary relief for breaches",
      cla_meta: "<p>Available remedies and enforcement</p>",
      cla_playbook: "<p>Irreparable harm language supports requests for injunctive relief, helping overcome procedural requirements that typically require showing monetary damages are inadequate. Bond waiver is significant - eliminates potential barrier to obtaining emergency relief (bonds can be $25K-$100K+). Consider whether specific performance is appropriate (generally yes for return/destruction obligations). Cumulative remedies language clarifies that injunction doesn't waive right to damages. Recipients sometimes negotiate for mutual application or limits on injunctive relief. Consider whether prevailing party should recover attorneys' fees (can be one-sided or mutual).</p>",
      cla_fallback: "Available remedies limited to monetary damages",
      cla_accountable: "Legal",
      cla_approval: true,
      cla_text__vs: "<p>The RECIPIENT acknowledges that any breach of this AGREEMENT would cause irreparable harm to the DISCLOSER for which monetary damages would be an inadequate remedy. In addition to all other remedies available at law or in equity, the DISCLOSER shall be entitled to seek specific performance and injunctive relief. If the DISCLOSER prevails in any action to enforce this AGREEMENT, the RECIPIENT shall reimburse the DISCLOSER for all reasonable attorneys' fees and costs incurred.</p>",
      cla_approval__vs: false,
      cla_comment: null,
      cla_comment__vs: "Fee shifting provision may need to be mutual rather than one-sided; consider whether bond requirement should remain",
      cla_compare: "Version 2 adds prevailing party attorneys' fees recovery (one-sided in favor of Discloser) but removes bond waiver.",
      cla_timestamp: "2020-12-02T10:30:00Z",
      cla_updated: false
    }
  ],

  // Signatures
  signatures: [
    {
      sig_index: 1,
      sig_con_index: 6,
      sig_party_index: 1,
      sig_party_name: "ndaDesk GmbH",
      sig_signatory_name: "Philipp Fontaine",
      sig_signatory_title: "Managing Director",
      sig_date: null,
      sig_status: "pending",
      sig_ip_address: null,
      sig_timestamp: null
    },
    {
      sig_index: 2,
      sig_con_index: 6,
      sig_party_index: 2,
      sig_party_name: "Dirk Hoffmann Consulting GbR",
      sig_signatory_name: "Dirk Hoffmann",
      sig_signatory_title: "Partner",
      sig_date: null,
      sig_status: "pending",
      sig_ip_address: null,
      sig_timestamp: null
    }
  ],

  // Workflow and Status Tracking
  workflow: {
    workflow_index: 1,
    con_index: 6,
    current_stage: "legal_review",
    stages: [
      {
        stage_index: 1,
        stage_name: "draft",
        stage_status: "completed",
        stage_completed_date: "2020-11-23T14:30:00Z",
        stage_completed_by: "Michael Zollner",
        stage_order: 1
      },
      {
        stage_index: 2,
        stage_name: "legal_review",
        stage_status: "in_progress",
        stage_start_date: "2020-12-01T09:00:00Z",
        stage_reviewer: "Michael Zollner",
        stage_expected_completion: "2020-12-10T17:00:00Z",
        stage_order: 2
      },
      {
        stage_index: 3,
        stage_name: "stakeholder_review",
        stage_status: "pending",
        stage_expected_start: "2020-12-10T09:00:00Z",
        stage_order: 3
      },
      {
        stage_index: 4,
        stage_name: "negotiation",
        stage_status: "pending",
        stage_expected_start: "2020-12-20T09:00:00Z",
        stage_order: 4
      },
      {
        stage_index: 5,
        stage_name: "execution",
        stage_status: "pending",
        stage_expected_start: "2021-01-15T09:00:00Z",
        stage_order: 5
      }
    ]
  },

  // Comments/Discussion Threads
  comments: [
    {
      comment_index: 1,
      comment_con_index: 6,
      comment_entity_type: "definition",
      comment_entity_index: 202,
      comment_user_id: "user-789",
      comment_user_name: "Sarah Mueller",
      comment_user_role: "Operations Manager",
      comment_text: "Should we expand AUTHORIZED ACCESS to explicitly include subcontractors? We often use third-party implementation partners.",
      comment_parent_index: null,
      comment_created_at: "2020-11-25T10:15:00Z",
      comment_resolved: false
    },
    {
      comment_index: 2,
      comment_con_index: 6,
      comment_entity_type: "definition",
      comment_entity_index: 202,
      comment_user_id: "user-456",
      comment_user_name: "Michael Zollner",
      comment_user_role: "Legal Counsel",
      comment_text: "Good point. I think we should add that but require they sign separate NDAs. Will draft language for version comparison.",
      comment_parent_index: 1,
      comment_created_at: "2020-11-25T14:30:00Z",
      comment_resolved: false
    },
    {
      comment_index: 3,
      comment_con_index: 6,
      comment_entity_type: "clause",
      comment_entity_index: 302,
      comment_user_id: "user-234",
      comment_user_name: "Klaus Schmidt",
      comment_user_role: "CISO",
      comment_text: "The encryption requirement is good, but we should specify TLS 1.3 or higher and AES-256 for data at rest. This is our standard requirement.",
      comment_parent_index: null,
      comment_created_at: "2020-11-26T11:45:00Z",
      comment_resolved: false
    },
    {
      comment_index: 4,
      comment_con_index: 6,
      comment_entity_type: "clause",
      comment_entity_index: 314,
      comment_user_id: "user-567",
      comment_user_name: "Petra Hoffmann",
      comment_user_role: "Business Development",
      comment_text: "Three year term seems long for our typical NDAs with consulting firms. Can we negotiate down to 2 years?",
      comment_parent_index: null,
      comment_created_at: "2020-11-27T09:20:00Z",
      comment_resolved: false
    },
    {
      comment_index: 5,
      comment_con_index: 6,
      comment_entity_type: "clause",
      comment_entity_index: 314,
      comment_user_id: "user-456",
      comment_user_name: "Michael Zollner",
      comment_user_role: "Legal Counsel",
      comment_text: "The 3-year term aligns with the confidentiality period. However, we can discuss this with the counterparty if it's a sticking point.",
      comment_parent_index: 4,
      comment_created_at: "2020-11-27T14:15:00Z",
      comment_resolved: false
    },
    {
      comment_index: 6,
      comment_con_index: 6,
      comment_entity_type: "preamble",
      comment_entity_index: 1,
      comment_user_id: "user-890",
      comment_user_name: "Thomas Weber",
      comment_user_role: "Contracts Manager",
      comment_text: "We need to fill in the specific contract type and date before sending to counterparty. Do we have the MSA executed yet?",
      comment_parent_index: null,
      comment_created_at: "2020-11-28T08:30:00Z",
      comment_resolved: false
    }
  ],

  // Change History/Audit Log
  change_history: [
    {
      change_index: 1,
      change_con_index: 6,
      change_entity_type: "clause",
      change_entity_index: 314,
      change_timestamp: "2020-11-30T16:45:00Z",
      change_user_id: "user-456",
      change_user_name: "Michael Zollner",
      change_action: "create_version",
      change_field: "cla_text__vs",
      change_old_value: null,
      change_new_value: "<p>This AGREEMENT shall commence on the Effective Date and shall continue for a period of five (5) years...</p>",
      change_comment: "Created alternative version with 5-year term and convenience termination per counterparty's initial request"
    },
    {
      change_index: 2,
      change_con_index: 6,
      change_entity_type: "clause",
      change_entity_index: 302,
      change_timestamp: "2020-11-29T11:20:00Z",
      change_user_id: "user-456",
      change_user_name: "Michael Zollner",
      change_action: "create_version",
      change_field: "cla_text__vs",
      change_old_value: null,
      change_new_value: "<p>The RECIPIENT shall implement and maintain security measures consistent with industry standards including ISO 27001...</p>",
      change_comment: "Added ISO 27001 requirement per CISO's security requirements - to be discussed with counterparty"
    },
    {
      change_index: 3,
      change_con_index: 6,
      change_entity_type: "definition",
      change_entity_index: 202,
      change_timestamp: "2020-11-28T14:10:00Z",
      change_user_id: "user-456",
      change_user_name: "Michael Zollner",
      change_action: "create_version",
      change_field: "def_value__vs",
      change_old_value: null,
      change_new_value: "<p>\"AUTHORIZED ACCESS\" means access to Confidential Information by those employees, contractors, consultants...</p>",
      change_comment: "Expanded to include contractors per Operations team feedback and added Discloser approval requirement"
    },
    {
      change_index: 4,
      change_con_index: 6,
      change_entity_type: "metadata",
      change_entity_index: 6,
      change_timestamp: "2020-11-23T10:00:00Z",
      change_user_id: "user-456",
      change_user_name: "Michael Zollner",
      change_action: "create",
      change_field: "status",
      change_old_value: null,
      change_new_value: "Draft",
      change_comment: "Initial draft created based on standard NDA template"
    }
  ]
};

// Export for use in module systems
if (typeof module !== "undefined" && module.exports) {
  module.exports = contractData;
}